<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Benzene.AspNet.Core" />
    <PackageReference Include="Benzene.Clients" />
    <PackageReference Include="Benzene.Microsoft.Dependencies" />
    <PackageReference Include="AWSSDK.DynamoDBv2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Contracts\Benzene.Patterns.TransactionalOutbox.Contracts.csproj" />
  </ItemGroup>
</Project>
