<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Benzene.AspNet.Core" />
    <PackageReference Include="Benzene.HostedService" />
    <PackageReference Include="Benzene.Http" />
    <PackageReference Include="Benzene.Microsoft.Dependencies" />
    <PackageReference Include="Benzene.SelfHost" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Shipping\Benzene.Patterns.ModularMonolith.Modules.Shipping.csproj" />
  </ItemGroup>

</Project>
